Console.WriteLine("Введите координаты x1");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координаты y1");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координаты x2");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координаты y2");
int y2 = Convert.ToInt32(Console.ReadLine());
double z = Math.Sqrt(Math.Pow((x2 - x1), 2) + Math.Pow((y2 - y1), 2));
Console.WriteLine($"Расстояние между точками: {z}");
